### PR TITLE
Bug/44/remove fixed tfs

### LINKED ISSUE #44: Remove FixedTfs
FixedTfs does not work with pandas 1.0 and newer. Pandas are getting more flexible. Fix seems to require quite deep digging and redefinition of basic pandas.DataFrame methods. If resolved the behaviour of FixedTfs and of TfsDataFrame will diverge. Different behaviour may be misleading since the use cases are very similar, if not the same. 
Now the questions to answer are: 
 - Is anyone actually using FixedTfs?
-  If so, is it worth the effort to make it work with newer pandas?
-  Or we just get rid of it?

### PR DESCRIPTION
**Pull request by lmalina**
Fixes #44 #29 and #45.

### CODE REVIEW

**Review by Mael-Le-Garrec — APPROVED** [review]
👍
